apiVersion: v1
kind: Service
metadata:
  name: account-service-api
  namespace: boathouse-prod
spec:
  type: LoadBalancer
  ports:
  - port: 7002
    targetPort: 8080 
  selector:
    app: account-service-api

