apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: boathouse-prod
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - image: docker.pkg.github.com/#{BOATHOUSE_ORG_NAME}#/boat-house/client:#{env.BRANCH_NAME}#-#{env.BUILD_ID}#
        name: client
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
